server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: mobihub-load-test
  profile:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  platform:
    platform-url: ${PLATFORM_URL:http://localhost:8081}
    inventory:
      url: http://localhost:8081/api/inventory #https://mobihubtestapi.comodif.com/platform/api/inventory
    vehicle:
      url: http://localhost:8081/api/vehicles
    device:
      url: http://localhost:8081/api/devices
  user-service:
    user-service-url: ${USER_SERVICE_URL:http://localhost:8080}
    auth:
      url: http://localhost:8080
  device-rest-service:
    device-rest-service-url: ${DEVICE_REST_SERVICE_URL:http://localhost:8191}
  security:
    admin:
      tenant: Y29tb2RpZg
      bearer: ${ADMIN_BEARER:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBjb21vZGlmLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwidXNlcklkIjoxLCJ0ZW5hbnQiOiJZMjl0YjJScFpnIiwiand0VVVJRCI6IjAxNjliNjk1LWNmZjItNDBjYi1iNjAzLWM1MjY4MzFkNzFkOCJ9.pQ26QmQsvL_E9QUIUaAPhmvNdL_DjByvWpysMjEBGYY}
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_NAME:postgres}?ssl=false&loginTimeout=30
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  cassandra:
    compression: lz4
    contact-points: localhost
    port: 9042
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1
    keyspace-name: connectivity_3
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    consistency-level: LOCAL_ONE  # Consistency level'ı değiştirdik

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
  config: ${LOGGING_CONFIG:classpath:logback-spring-dev.xml}

mqtt:
  client-id: mqttLocalClient1
  username: admin
  password: admin
  broker-urls: tcp://localhost:1883 #tcp://91.194.54.42:1883
  topics: ${MQTT_TOPICS:v1/devices/me/telemetry}
  command-topic: v1/devices/me/rpc/request/
  load-test:
    filePath: /Users/berkantkubat/Desktop/comodif/mobihub3/mobihub-load-test/erol-istanbul.json
    maxConcurrentDevices: 50
    messageIntervalMillis: 50
    connectionRetryDelay: 5000
    maxConnectionRetries: 3
